apiVersion: v1
kind: Service
metadata:
  name: crdb
  labels:
    app: crdb
spec:
  ports:
  - port: 26257
    targetPort: 26257
    name: grpc
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: crdb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crdb
spec:
  selector:
    matchLabels:
      app: crdb
  serviceName: "crdb"
  replicas: 3
  template:
    metadata:
      labels:
        app: crdb
    spec:
      containers:
      - name: crdb
#        for arm
#        image: quay.io/ecordell/crdb:arm2
        image: cockroachdb/cockroach:v21.1.8
        command:
          - "/bin/bash"
          - "-ecx"
          - exec
            ./cockroach
            start
            --logtostderr
            --insecure
            --advertise-addr $(hostname -f)
            --http-addr 0.0.0.0
            --join crdb-0.crdb,crdb-1.crdb,crdb-2.crdb
        ports:
        - containerPort: 26257
          name: crdb