---
name: "Build & Test"
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
jobs:
  lint:
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/setup-go@v2"
        with:
          go-version: "^1.17"
      - name: "Install linting tools"
        run: |
          # This is done before checking out, as to not modify go.mod
          go install mvdan.cc/gofumpt/gofumports@latest
          go install github.com/mgechev/revive@latest
          go install golang.org/x/tools/cmd/stringer@latest
      - uses: "actions/checkout@v2"
      - uses: "bewuethr/yamllint-action@v1.1.1"
        with:
          config-file: ".yamllint"
      - name: "Go Mod Tidy"
        run: "go mod tidy && bash -c '[ $(git status --porcelain | tee /dev/fd/2 | wc -c) -eq 0 ]'"
      - name: "Formatting (gofumpt)"
        run: |
          GOFUMPT_OUTPUT="$(find . -iname '*.go' -type f | grep -v pb.validate.go | grep -v pb.go | xargs gofumports -d)"
          if [ -n "$GOFUMPT_OUTPUT" ]; then
            echo "All the following files are not correctly formatted"
            echo "${GOFUMPT_OUTPUT}"
            exit 1
          fi
      - name: "Linting (revive)"
        run: "revive ./..."
      - name: "Go Generate"
        run: "go generate ./... && bash -c '[ $(git status --porcelain | tee /dev/fd/2 | wc -c) -eq 0 ]'"

  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-go@v2"
        with:
          go-version: "^1.17"
      - name: "Build"
        run: |
          go build ./cmd/crdb-migration
          go build ./cmd/spicedb
      - name: "Test"
        run: "go test ./..."
      - name: "Full Datastore Integration Tests"
        run: "go test -tags ci ./..."

  e2e:
    name: "E2E"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-go@v2"
        with:
          go-version: "^1.16"
      - name: "Install kind"
        run: |
          curl -sLo kind "$(curl -sL https://api.github.com/repos/kubernetes-sigs/kind/releases/latest | jq -r '[.assets[] | select(.name == "kind-linux-amd64")] | first | .browser_download_url')"
          chmod +x kind
          sudo mv kind /bin/
      - name: "Run e2e"
        run: |
          pushd e2e/newenemy
          ./run.sh
          popd
      - name: Archive test logs
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: node-logs
          path: e2e/newenemy/*.log

  protobuf:
    name: "Generate Protobufs"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-go@v2"
        with:
          go-version: "^1.17"
      - name: "Install Go Protobuf plugins"
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
          go install github.com/envoyproxy/protoc-gen-validate@v0.6.1
      - uses: "bufbuild/buf-setup-action@v0.3.1"
        with:
          version: "0.52.0"
      - name: "Generate & Diff Protos"
        run: "./buf.gen.yaml && git diff && bash -c '[ $(git status --porcelain | tee /dev/fd/2 | wc -c) -eq 0 ]'"
      - uses: "bufbuild/buf-breaking-action@v0.4.0"
        if: "github.event_name == 'pull_request'"
        env:
          BUF_INPUT_HTTPS_USERNAME: "${{ github.actor }}"
          BUF_INPUT_HTTPS_PASSWORD: "${{ github.token }}"
        with:
          input: "proto/internal"
          against: "https://github.com/authzed/spicedb.git#branch=main,subdir=proto/internal"
          buf_token: "${{ secrets.BUF_REGISTRY_TOKEN }}"

  image-build:
    name: "Verify Image"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"
      - uses: "docker/setup-qemu-action@v1"
      - uses: "docker/setup-buildx-action@v1"
        with:
          driver-opts: "image=moby/buildkit:master"
      - name: "Build the container image"
        uses: "docker/build-push-action@v1"
        with:
          push: false
